name: Rash
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build, Test & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - run: npm ci
      - run: npm run compile --if-present
        #      - run: npm run test
        env:
          CI: true
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch -m "automated version bump - %s" -f
          git branch --set-upstream-to=origin/master
          git status
          npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
